### PR TITLE
1 link to nomad simulations

### PR DESCRIPTION
**Pull request by JFRudzinski**

### CODE REVIEW

**Comment by JosePizarro3** [comment]
Hi @JFRudzinski , watch out because you are linking your plugin's pull requests to the parser, instead of your @develop or whatever main branch you have in the `nomad-parser-h5md` plugin.

**Comment by JFRudzinski** [comment]
> Hi @JFRudzinski , watch out because you are linking your plugin's pull requests to the parser, instead of your @develop or whatever main branch you have in the `nomad-parser-h5md` plugin.

Thank you!! It's so weird, at some point my PR got mirrored or shifted from my parser plugin repo https://github.com/nomad-coe/nomad-parser-h5md/pull/2 to here in the parser-plugin-example repo :thinking: :fearful:

**Comment by JFRudzinski** [comment]
@JosePizarro3 are you sure that something is wrong? My parser plugin repo seems to be tracking everything accurately: https://github.com/nomad-coe/nomad-parser-h5md/pull/2  I don't really know what is supposed to happen when you are working on a forked repo, am I supposed to disconnect the fork somehow?

**Comment by JosePizarro3** [comment]
> @JosePizarro3 are you sure that something is wrong?

Well, we are talking in a pull request in the nomad-parser-plugin-example 😁 @blueraft would you mind helping us and telling us what might have happened?

**Comment by blueraft** [comment]
Yep, this is in an issue with Github forks. If you make a PR to a forked repo, the default target will be to the original repo (in this case the nomad-parser-example) instead of the fork. You should just close this PR: the other [PR](https://github.com/nomad-coe/nomad-parser-h5md/pull/2) looks correct to me.

**Comment by JFRudzinski** [comment]
> > @JosePizarro3 are you sure that something is wrong?
> 
> Well, we are talking in a pull request in the nomad-parser-plugin-example 😁 @blueraft would you mind helping us and telling us what might have happened?

haha, indeed, just checking, I very much do not understand :dizzy_face:

**Comment by JFRudzinski** [comment]
> forked repo, the default target will be to the original repo (in this case the nomad-parser-example) instead o

Thanks for the quick reply. Is it normal though for the PR to be mirrored? I only created 1 PR in the forked repo not here. It seems to have duplicated it and all my pushed automatically. I checked the remote address and such of my local repo it all seems to correspond to the forked repo.

**Comment by JFRudzinski** [comment]
To be clear, I am just asking to make sure it will not happen again, but I guess I can just keep an eye on it

**Comment by blueraft** [comment]
I think while creating the PR it was automatically targeting the `nomad-parser-plugin-repo` and you may not have realized that. The two PRs are the same branch from the forked repo so there's nothing wrong on your end there, just a misclick when you initially created the PR probably.

**Pull request closed without merging**
